[tasks.compile]
description = "Build"
workspace = false
command = "cargo"
args = ["build"]

[tasks.compile_release]
description = "Release Build"
extend = "compile"
args = ["build", "--release"]

[tasks.deploy_local]
description = "deploy binary file"
workspace = false
script = ['''
#!/usr/bin/env bash
rm -f ~/bin/tsundoku-accelerator/*
cp -p ./target/release/backend-cli ~/bin/tsundoku-accelerator/
''']
dependencies = ["compile_release"]
