version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tsundoku-accelerator-backend"
s3_bucket = "tsundoku-accelerator-backend"
s3_prefix = "tsundoku-accelerator-backend"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []