-- AlterTable
ALTER TABLE "Ebook" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "EbookSnapshot" ALTER COLUMN "scrapedAt" SET DATA TYPE BIGINT,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "discount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "discountRate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "points" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pointsRate" SET DATA TYPE DOUBLE PRECISION;
