[package]
name = "comannds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
envy = "0.4.2"
headless_chrome = "1.0.4"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.1" }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.1" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
url = "2.2.2"
futures = "0.3.24"
once_cell = "1.15.0"
regex = "1.6.0"
libmath = "0.2.1"
webhook = "2.1.1"
chrono = "0.4.23"
db_client = { path = "../db_client" }
scraper = { path = "../scraper" }
log = "0.4.0"
env_logger = "0.10.0"

[dev-dependencies]
insta = "1.21.0"
